version: '3'
services:
  nginx:
    image: "nginx"
    ports:
      - "8080:80"
    volumes:
      - ./dev/nginx.conf:/etc/nginx/nginx.conf
      - ./ui:/usr/share/nginx/html
    depends_on:
      - metadatastore
      - api

  redis:
    image: "redis"
    ports:
      - "6379:6379"

  metadatastore:
    build: ./metadatastore
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - ./metadatastore:/app
    depends_on:
      - redis

  api:
    build: ./api
    command: go run main.go
    environment:
      - METADATASTORE_URL=http://metadatastore:3000
    ports:
      - "8000:8000"
    volumes:
      - ./api:/go
    depends_on:
      - metadatastore